<?php
$config=array (
  'bitfire_enabled' => true,
  'allow_ip_block' => 'on',
  'security_headers_enabled' => 'report',
  'enforce_ssl_1year' => 'report',
  'feature_policy' => false,
  'allowed_features' => 
  array (
    'notifications' => 'self',
    'push' => 'self',
    'geolocation' => 'self',
  ),
  'max_cache_age' => 0,
  'web_filter_enabled' => true,
  'decode_html' => true,
  'spam_filter_enabled' => 'report',
  'xss_block' => true,
  'sql_block' => 'block',
  'web_block' => true,
  'file_block' => true,
  'block_profanity' => false,
  'filtered_logging' => 
  array (
    'cc' => true,
    'card' => true,
    'cardnumber' => true,
    'exp' => true,
    'expiration' => true,
    'cvv' => true,
    'cvv1' => true,
    'cvv2' => true,
    'pass' => true,
    'password' => true,
    'password1' => true,
    'password2' => true,
  ),
  'botwhitelist' => 
  array (
    'googlebot' => 'google(bot?).com',
    'zoominfobot' => 'googleusercontent.com',
    'bingbot' => '(microsoft.com|msn.com)',
    'yahoo' => 'yahoo.com',
    'duckduckbot' => 'duckduckgo.com',
    'baidu' => 'baidu.(com.jp)',
    '360spider' => 'baidu.(com.jp)',
    'uptimerobot' => 'uptimerobot.com',
    'applebot' => 'apple.com',
    'redditbot' => 'reddit.com',
    'naver.com' => 'naver.com',
    'yeti' => 'naver.com',
    'statuscake' => 'vultr.com',
    'yandex' => 'yandex.(ru|net|com)',
    'sogou.com' => 'sogou.com',
    'exabot' => 'exalead.com',
    'linkedinbot' => '(linkedin.com|microsoft.com|msn.com)',
    'facebookexternalhit' => 'AS32934',
    'appengine; appid: s~snapchat-proxy)' => '35\\.187\\.*\\.*',
    'tumblr' => 'AS2635',
    'whatsapp' => 'AS32934',
    'twitterbot' => 'AS13414',
    'embedly' => 'embed.ly',
    'gigabot' => 'gigablast.com',
    'alexa' => 'alexa.com',
    'jeeves' => 'ask.com',
    'aolbuild' => 'aol.com',
    'archive.org' => 'archive.org',
    'Pintrest' => 'pintrest.com',
    'curl' => '127.0.0.1,192.168.*,10.*',
    'wget' => '127.0.0.1,192.168.*,10.*',
    'observatory' => 'mozilla.com',
    'ahrefsbot' => 'ahrefs.com',
  ),
  'allowed_methods' => 
  array (
    0 => 'GET',
    1 => 'OPTIONS',
    2 => 'POST',
    3 => 'PUT',
    4 => 'HEAD',
  ),
  'whitelist_enable' => true,
  'blacklist_enable' => true,
  'require_full_browser' => 'on',
  'honeypot_url' => '/ztcegizz/contact',
  'check_domain' => false,
  'valid_domains' => 
  array (
    0 => 'localhost',
    1 => '127.0.0.1',
  ),
  'rate_limit' => 'report',
  'rr_1m' => 25,
  'rr_5m' => 50,
  'cache_type' => 'shmop',
  'report_file' => '/tmp/would_block.json',
  'block_file' => '/tmp/block.json',
  'debug_file' => false,
  'bitfire_param' => '_kbuqyrkc',
  'browser_cookie' => '_ltfc',
  'block_page' => 'blocked.php',
  'dashboard_path' => '/bitfire',
  'encryption_key' => 'PzYSeYq99o8iuzHny6YdsCT2',
  'secret' => 'RNQNeCaMExTKHPEI',
  'password' => 'default_password',
  'debug' => true,
  'web_uid' => 33,
  'response_code' => 403,
  'ip_header' => 'REMOTE_ADDR',
  'dns_service' => 'localhost',
  'short_block_time' => 600,
  'medium_block_time' => 3600,
  'long_block_time' => 86400,
);
